# Generated by Django 3.2.8 on 2021-11-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.FileField(default='Profile/User.jpg', upload_to='Profile/ProfilePic/'),
        ),
    ]
