# Generated by Django 3.2.8 on 2021-11-10 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hate',
            field=models.ManyToManyField(blank=True, related_name='commenthate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='commentlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='love',
            field=models.ManyToManyField(blank=True, related_name='commentlove', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rply',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.reply'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='hate',
            field=models.ManyToManyField(blank=True, related_name='hate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='love',
            field=models.ManyToManyField(blank=True, related_name='love', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='hate',
            field=models.ManyToManyField(blank=True, related_name='replyhate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='replylike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='love',
            field=models.ManyToManyField(blank=True, related_name='replylove', to=settings.AUTH_USER_MODEL),
        ),
    ]
