# Generated by Django 3.2.8 on 2021-11-11 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20211110_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='posts',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='view', to=settings.AUTH_USER_MODEL),
        ),
    ]
