# Generated by Django 3.2.8 on 2021-11-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sub',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
