# Generated by Django 3.2.8 on 2021-11-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20211111_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='commentss',
        ),
        migrations.AddField(
            model_name='posts',
            name='commentss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comment'),
        ),
    ]
