# Generated by Django 3.2.8 on 2021-11-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_comment_rply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='commentss',
        ),
        migrations.AddField(
            model_name='posts',
            name='commentss',
            field=models.ManyToManyField(blank=True, null=True, to='post.Comment'),
        ),
    ]
