# Generated by Django 3.2.8 on 2021-11-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20211113_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-saon']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rply',
        ),
        migrations.AddField(
            model_name='comment',
            name='rply',
            field=models.ManyToManyField(blank=True, null=True, related_name='replys', to='post.Reply'),
        ),
    ]
