# Generated by Django 3.2.8 on 2021-11-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20211113_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
